from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.base import MIMEBase
import os
import smtplib
from email import encoders
from dotenv import load_dotenv
load_dotenv()
mail_from = os.environ.get('mail_from')
from_addr = os.environ.get('from_addr')
to_addr =  "s.devi@lgb.co.in" #os.environ.get('to_addr').split(',')
mail_pwd = os.environ.get('mail_pwd')
server_name = os.environ.get('server_name')
port = os.environ.get('port')
def send_mail():
	subject = "Reg : TVS Yesterday's Sales  - Report Not Yet Received"
	body = """<html>
				<body>
				<caption>Sir/Madam,</caption><br>
				<p>This is common mail, could not  ssl shaked 
				,So please check </p><br>
				<p>Note : This is an autogenerated mail. Please do not respond to this.</p>
				</body>
				</html>"""
	message = MIMEMultipart()
	message["From"] = mail_from
	message["To"] =  "to_addr" #','.join(to_addr)
	message["Subject"] = subject
	message.attach(MIMEText(body, "html"))
	text = message.as_string()
	with smtplib.SMTP(server_name, port) as server:
		server.starttls() 
		server.login(from_addr, mail_pwd)
		server.sendmail(mail_from, to_addr , text)
		server.quit()
send_mail()