from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.base import MIMEBase
import os
import smtplib
from email import encoders
from dotenv import load_dotenv
load_dotenv()
mail_from = os.environ.get('mail_from')
from_addr = os.environ.get('from_addr')
to_addr =  os.environ.get('to_addr').split(',')
ccaddr = os.environ.get('ccaddr').split(',')
mail_pwd = os.environ.get('mail_pwd')
server_name = os.environ.get('server_name')
port = os.environ.get('port')
def send_mail():
	subject = "Reg : TVS Report - Password Issue"
	body = """<html>
  <body style="font-family: Arial, sans-serif; font-size: 14px; color: #333;">
    <p>Dear Sir/Madam,</p>

    <p>This is an automated report regarding the TVS system.</p>

    <p>
      Please note that the password provided is not valid. Kindly verify the credentials and try again.
    </p>

    <p style="color: #888;"><em>Note: This is an autogenerated email. Please do not reply to this message.</em></p>
  </body>
</html>
"""
	message = MIMEMultipart()
	message["From"] = mail_from
	message["To"] = ','.join(to_addr)
	message['Cc'] = ','.join(ccaddr)
	message["Subject"] = subject
	message.attach(MIMEText(body, "html"))
	text = message.as_string()
	with smtplib.SMTP(server_name, port) as server:
		server.starttls() 
		server.login(from_addr, mail_pwd)
		server.sendmail(mail_from, to_addr , text)
		server.quit()
send_mail()